Shell script driver

diff --git a/castty b/castty
--- a/castty
+++ b/castty
@@ -1,448 +1,39 @@
 #!/bin/sh -e
 
 
-###############
-## CONSTANTS ##
-###############
-CASTTY_BASEDIR=$(dirname "$0")
-CASTTY_MK="$CASTTY_BASEDIR/castty.mk"
-CASTTY_RECDIR="rec"
-CASTTY_SRCDIR="src"
-CASTTY_CLIPDIR="clip"
-CASTTY_NJOBS="$((`nproc`))"
-CASTTY_FIFO="$CASTTY_RECDIR/fifo"
 
-alias ffmpeg="ffmpeg -hide_banner"
 
-###################
-## CONFIGURATION ##
-###################
+castty_kill() {
+    F="/var/run/user/$(id -u)/castty.pid"
+    if [ -e "${F}" ]; then
+        xargs -n 1 kill < ${F} && rm "${F}"
+    fi
+}
 
-if [ -f "$HOME/.config/casttyrc" ]; then
-    . "$HOME/.config/casttyrc"
+
+castty_run() {
+    export CASTTY_COMMAND
+
+    exec sbcl --noinform --disable-debugger --disable-ldb --lose-on-corruption --noprint \
+         <<EOF
+         (require 'castty)
+         (castty::driver)
+EOF
+}
+
+
+
+CASTTY_COMMAND="$1"
+if [ -z "${CASTTY_COMMAND}" ] ; then
+   >&2 echo "ERROR: No command given"
+   exit 1
 fi
 
-if [ -z "$CASTTY_FILTER" ]; then
-    # Assume we're doing compression and noise-gating in hardware, so just
-    # do a simple filter and loudness normalization
-    CASTTY_FILTER="highpass=f=80"
-    CASTTY_FILTER="$CASTTY_FILTER,lowpass=f=12000"
-    CASTTY_FILTER="$CASTTY_FILTER,loudnorm"
-fi
-
-
-## DEFAULTS ##
-
-# AUDIO
-: ${CASTTY_AUDIO_DEVICE:=pulse}
-: ${CASTTY_AUDIO_INPUT:=default}
-: ${CASTTY_AUDIO_PASUSPEND:=no}
-
-export CASTTY_AUDIO_INPUT
-export CASTTY_AUDIO_DEVICE
-export CASTTY_FILTER
-
-# VIDEO
-: ${CASTTY_VIDEO_FPS:=15}
-: ${CASTTY_VIDEO_DEVICE:=x11grab}
-: ${CASTTY_VIDEO_SIZE:=1920x1080}
-: ${CASTTY_VIDEO_FPS:=15}
-: ${CASTTY_VIDEO_INPUT:=:0.0}
-
-
-export CASTTY_VIDEO_FPS
-export CASTTY_VIDEO_DEVICE
-export CASTTY_VIDEO_SIZE
-export CASTTY_VIDEO_FPS
-export CASTTY_VIDEO_INPUT
-
-castty_screenshot() {
-    f="$CASTTY_RECDIR/$1"
-    ffmpeg -f "$CASTTY_VIDEO_DEVICE" \
-           -video_size "$CASTTY_VIDEO_SIZE" \
-           -framerate 30 \
-           -i "$CASTTY_VIDEO_INPUT" \
-           -vframes 1 \
-           "$f"
-}
-
-
-castty_overlay() {
-    # Get Command Line Arguments
-    while [ "$1" != "" ]; do
-        case "$1" in
-            -n) # Output clip number
-                num="$2"
-                v="$CASTTY_SRCDIR/video-$num.mkv"
-                a="$CASTTY_SRCDIR/audio-$num.flac"
-                b="$CASTTY_SRCDIR/bg-$num.png"
-                o="$CASTTY_CLIPDIR/clip-$num.mkv"
-                shift
-                shift
-                ;;
-            *)
-                echo " ERROR: invalid argument \`$1'"
-                exit 1
-                ;;
-        esac
-    done
-
-    ## TODO: parameters for size and offset
-    ffmpeg  -i "$v"  -i "$b" -i "$a" \
-            -filter_complex \
-            "[0:v]scale=1440:810[outv];[1:v][outv]overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2+75[outvx]" \
-            -map '[outvx]:v:0' -map 2:a:0 \
-            -c:a copy \
-            -c:v libx264 -qp 0 "$o"
-}
-
-
-castty_ingestpdf() {
-
-    mkdir -p "$CASTTY_CLIPDIR"/slides
-               #-scale-to-y 1080 \
-    # Quirk: resolution is off by one, does not match screenshots
-    pdftocairo -png \
-               -cropbox \
-               src/slides.pdf \
-               -scale-to 1920 \
-               "$CASTTY_CLIPDIR"/slides/slide
-}
-
-
-# Transcode source files
-castty_ingest() {
-    # for i in $CASTTY_RECDIR/slide-*.ogv; do
-    #     CASTTY_FILES="$CASTTY_FILES $CASTTY_SRCDIR/$(basename -s .ogv $i).mkv"
-    # done
-
-    mkdir -p "$CASTTY_SRCDIR"
-
-    ## VIDEO
-    echo Ingesting video...
-
-    # raw video
-    for i in $CASTTY_RECDIR/*.nut.zst; do
-        test -f "$i" \
-            && zstd -T0 -qdc "$i"  \
-                | \
-                ffmpeg -i - \
-                       -c:v libx264 -qp 0  \
-                       "$CASTTY_SRCDIR/$(basename -s .nut.zst $i).mkv" \
-            && rm -v "$i"
-    done
-
-    # screenshots
-    for i in $CASTTY_RECDIR/*.png; do
-        test -f "$i" \
-            && mv "$i" "$CASTTY_SRCDIR"
-    done
-
-
-    ## AUDIO
-    echo Ingesting audio...
-    for i in $CASTTY_RECDIR/*.wav; do
-        test -f "$i" \
-            && ffmpeg -i "$i" \
-                      -c:a flac \
-                      "$CASTTY_SRCDIR/$(basename -s .wav $i).flac" \
-            && rm -v "$i"
-    done
-
-
-    ## CLIPS
-    mkdir -p "$CASTTY_CLIPDIR"
-    echo Combining clips....
-    for v in $CASTTY_SRCDIR/video-*.mkv  $CASTTY_SRCDIR/video-*.png; do
-        if [ -f "$v" ]; then
-            b=$(basename "$v")
-            bb=$(echo "$b" | cut -d '.' -f 1)
-            s=$(echo "$b" | cut -d '.' -f 2)
-            num=$(echo "$bb" | sed  -e 's!video-\([^/]*\)$!\1!')
-            a="$CASTTY_SRCDIR/audio-$num.flac"
-            bg="$CASTTY_SRCDIR/bg-$num.png"
-            o="$CASTTY_CLIPDIR/clip-$num.mkv"
-
-            if [ ! -e "$o" ] ; then
-                if [ -f "$bg" ] ; then
-                    castty_overlay -n "$num"
-                else
-                    case "$s" in
-                        mkv)
-                            ffmpeg -i "$v" -i "$a" \
-                                   -map 0:v:0 -map 1:a:0 \
-                                   -c:v copy  -c:a copy \
-                                   "$o"
-                            ;;
-                        png)
-                            ffmpeg -i "$v" -i "$a" \
-                                   -map 0:v:0 -map 1:a:0 \
-                                   -framerate "$CASTTY_VIDEO_FPS" \
-                                   -c:v libx264 -qp 0    \
-                                   -c:a copy \
-                                   "$o"
-                            ;;
-                    esac
-                fi
-            fi
-        fi
-    done
-}
-
-
-
-# Postprocess
-castty_post() {
-    # All source files
-    for i in "$CASTTY_CLIPDIR"/clip-*.mkv; do echo "file '$i'"; done  > inputs.txt
-
-    mkdir -p out
-
-    # Concatenate
-    ffmpeg -f concat -i inputs.txt \
-           -codec:v libx264 -qp 0 \
-           -codec:a flac \
-           -framerate "$CASTTY_VIDEO_FPS" \
-           -ac 1 \
-           -max_muxing_queue_size 4096 \
-           out/cat.mkv
-
-    # Filter audio
-    ffmpeg -i out/cat.mkv \
-           -codec:a flac \
-           -filter:a "$CASTTY_FILTER" \
-           -max_muxing_queue_size 4096 \
-           out/filtered.flac
-
-    # Combine video and filtered audio
-    ffmpeg -i out/cat.mkv \
-           -i out/filtered.flac \
-           -map 0:v:0 -map 1:a:0 \
-           -codec:v copy \
-           -codec:a copy \
-           -max_muxing_queue_size 4096 \
-           out/hi-quality.mkv
-
-    # Re-encode audio
-    ffmpeg -i out/filtered.flac \
-           -filter:a aresample=48000 \
-           -codec:a pcm_s16le \
-           -f wav - \
-        | \
-        fdkaac --profile 2 --bitrate-mode 4  - -o out/compressed.m4a
-
-    # TODO: check compatibility on pixel format. YUV444 looks better
-    # but might need YUV420 for compatibility with most players.
-
-    # Transcode video and merge audio
-    ffmpeg -i out/cat.mkv \
-           -i out/compressed.m4a \
-           -map 0:v:0 -map 1:a:0 \
-           -codec:v libx264 -crf 23 \
-           -codec:a copy \
-           -max_muxing_queue_size 4096 \
-           out/compressed.mp4
-}
-
-castty_clean() {
-    rm -rf out clip
-}
-
-# Record
-castty_record() {
-    ## ARGUMENT VARIABLES
-    RECORD_AUDIO=yes
-    RECORD_VIDEO=yes
-    RECORD_SCREENSHOT=no
-    DRAW_MOUSE="-draw_mouse 0"
-
-    # Get Command Line Arguments
-    while [ "$1" != "" ]; do
-        case "$1" in
-            -o) # Output file
-                # OUTPUT_BASE=`echo "$2" | sed -e 's/\\.[^\\.]*$//'`
-                # OUTPUT="$CASTTY_RECDIR/$OUTPUT_BASE.ogv"
-                # OUTPUT_AUDIO="$CASTTY_RECDIR/$OUTPUT_BASE.flac"
-                OUTPUT="$2"
-                OUTPUT_BASE_VIDEO="$CASTTY_RECDIR/video-$OUTPUT"
-                OUTPUT_BASE_AUDIO="$CASTTY_RECDIR/audio-$OUTPUT"
-                shift
-                shift
-                ;;
-            -m)
-                DRAW_MOUSE="-draw_mouse 1"
-                shift
-                ;;
-            -s)
-                RECORD_SCREENSHOT=yes
-                RECORD_VIDEO=no
-                shift
-                ;;
-            -na) # no audio
-                RECORD_AUDIO=no
-                shift
-                ;;
-            -nv) # no video
-                RECORD_VIDEO=no
-                shift
-                ;;
-            # -nc) # TODO
-            #     RECORDMYDESKTOP_ARGS="$RECORDMYDESKTOP_ARGS --no-cursor"
-            #     shift
-            #     ;;
-            *)
-                echo " ERROR: invalid argument \`$1'"
-                exit 1
-                ;;
-        esac
-    done
-
-
-    ## SETUP ##
-    if [ "$CASTTY_AUDIO_PASUSPEND" = yes ]; then
-       CASTTY_DO_PASUSPEND="pasuspender --"
-       else
-           CASTTY_DO_PASUSPEND=""
-    fi
-    mkdir -p "$CASTTY_RECDIR"
-    PID_WAIT=""
-
-    # Video setup
-    if [ "$RECORD_VIDEO" = yes ] ; then
-        # Create FIFO
-        if [ -e "$CASTTY_FIFO" ]; then
-            >&2 echo "ERROR: '$CASTTY_FIFO' already exists"
-            exit 1
-        fi
-        mkfifo "$CASTTY_FIFO"
-
-        zstd --fast - \
-             < "$CASTTY_FIFO" \
-             > "$OUTPUT_BASE_VIDEO".nut.zst  &
-        PID_WAIT="$!"
-    fi
-
-    if [ "$RECORD_SCREENSHOT" = yes ] ; then
-        ffmpeg -f "$CASTTY_VIDEO_DEVICE" \
-               -video_size "$CASTTY_VIDEO_SIZE" \
-               -framerate 30 \
-               -i "$CASTTY_VIDEO_INPUT" \
-               $DRAW_MOUSE \
-               -vframes 1 \
-               "$OUTPUT_BASE_VIDEO".png
-    fi
-
-
-    ## CAPTURE ##
-    TIME_START=$(date '+%s.%3N')
-
-    # quirk: ffmpeg will return 255 when killed, so || with true
-
-    # Capture video
-    if [ "$RECORD_VIDEO" = yes ] ; then
-        ffmpeg \
-            -f "$CASTTY_VIDEO_DEVICE" \
-            $DRAW_MOUSE \
-            -video_size "$CASTTY_VIDEO_SIZE" \
-            -framerate "$CASTTY_VIDEO_FPS" \
-            -i "$CASTTY_VIDEO_INPUT" \
-            -codec:v rawvideo \
-            -f nut - \
-            > "$CASTTY_FIFO" || true &
-    fi
-
-    # Capture audio
-    if [ "$RECORD_AUDIO" = yes ] ; then
-        $CASTTY_DO_PASUSPEND ffmpeg \
-                             -f "$CASTTY_AUDIO_DEVICE" \
-                             -i "$CASTTY_AUDIO_INPUT" \
-                             -ac 1 \
-                             -codec:a pcm_s16le  \
-                             "$OUTPUT_BASE_AUDIO".wav \
-            || true
-    fi
-
-    TIME_END=$(date '+%s.%3N')
-
-    ## CLEANUP ##
-
-    # Wait for video to finish
-    if [ -n "$PID_WAIT" ] ; then
-        wait "$PID_WAIT"
-    fi
-
-    # Delete compression fifo
-    if [ -e "$CASTTY_FIFO" ]; then
-        rm "$CASTTY_FIFO"
-    fi
-
-    printf "WALL TIME: %0.3f sec\n" $(echo "$TIME_END" - "$TIME_START" | bc)
-
-    true
-
-    # if [ "$COMBINE" = yes ]; then
-    #     vlc -I  dummy --no-loop --play-and-exit "$OUTPUT_AUDIO" &
-    #     OUTPUT_VIDEO="$OUTPUT_BASE-tmp.ogv"
-    #     recordmydesktop $RECORDMYDESKTOP_ARGS \
-    #         --no-sound \
-    #         --fps "$FPS" \
-    #         --v_quality 63 \
-    #         --workdir /tmp \
-    #         --stop-shortcut "Mod1+s" \
-    #         --windowid "$WINDOW" -o "$OUTPUT_VIDEO"
-
-    #     ffmpeg -i "$OUTPUT_VIDEO" -i "$OUTPUT_AUDIO" \
-    #            -vcodec copy \
-    #            -acodec libvorbis -q:a 10  \
-    #            "$OUTPUT" \
-    #         && rm "$OUTPUT_VIDEO" \
-    #         && exit 0
-    # fi
-}
-
-
-
-castty_env () {
-    env | grep CASTTY
-}
-
-
-
-case "$1" in
-    ingest)
-        castty_ingest
-    ;;
-    ingestpdf)
-        shift
-        castty_ingestpdf "$@"
-    ;;
-    post)
-        castty_post
-    ;;
-    rec|record)
-        shift
-        castty_record "$@"
-    ;;
-    screenshot)
-        shift
-        castty_screenshot "$@"
+case "${CASTTY_COMMAND}" in
+    kill)
+        castty_kill
         ;;
-    bg)
-        shift
-        castty_screenshot "bg-$1.png"
-    ;;
-    overlay)
-        shift
-        castty_overlay "$@"
-    ;;
-    clean)
-        castty_clean
-    ;;
-    env)
-        castty_env
-    ;;
     *)
-        echo "ERROR: invalid command \`$1'"
-        exit 1
+        castty_run
         ;;
 esac
